name: SweetMail
version: '${version}'
main: top.mrxiaom.sweetmail.SweetMail
api-version: 1.13
softdepend:
  - Vault
  - PlaceholderAPI
  - MythicMobs
  - ItemsAdder
  - LangUtils
  - CraftEngine
  - ProtocolLib
authors: [ MrXiaoM ]
folia-supported: true
libraries:
  - "org.jetbrains:annotations:24.0.0"
commands:
  sweetmail:
    description: SweetMail main command.
    aliases: [sm, mail]

permissions:
  sweetmail.draft:
    default: true
  sweetmail.box:
    default: true
  sweetmail.notice:
    default: true
  sweetmail.icon.default:
    default: true
  sweetmail.price.default:
    default: true
  sweetmail.outdate.default:
    default: true
  sweetmail.draft.outdate.default:
    default: true
  sweetmail.format.color.basic:
    default: true
  sweetmail.attachment.item:
    default: true
